### ISSUE TITLE
Make the API simpler to use

### ISSUE THREAD

**Issue by sirMackk** [sirMackk/rsutils#1]
Looking at the first (only?) user of this API here https://github.com/sirMackk/rsbackup/blob/master/rs_file_manager.go#L134 it looks like rsutils could be refactored to present a simpler API.

One way to think about this is that users shouldn't have to duplicate the same work over and over again, so maybe a higher-level API would be better to save on setup time?

**Comment by sirMackk** [comment]
Some ideas:
- redo the SplitIntoFileChunks to do the size calculation internally, removing one argument to it and duplicate effort.
- fix error handling to pass better errors around
- does NewShardCreator really need to know the size of the data? Shouldn't padding/unpadding be the responsibility of the caller?

**Comment by prologic** [comment]
Hey @sirMackk ! I've been toying around with Reed Solomon in general and I'm also trying to come up with a better API that wraps the `reedsolomon.StreamEncoder` interface into something sane. I'm also trying to learn from your own code here.

it would be great if we could have an interface/API like:

```#!go
type Encoder interface {
  Encode(r io.Reader, ws []io.Writer) error
}
```

I'm not sure if it's possible to split and encode at the same time?

**Comment by sirMackk** [comment]
Hi @prologic! Thanks for checking out my code. Yeah, I'm also trying to figure out a better high-level interface for encoding/decoding.

I think the example you give can work, we would just need to pass in the number of data shards we want to split the original file into. That affects the size of parity shards - having 5 data shards and 2 parity shards means 40% of the data can be rebuilt, but having 10 data shards and 2 parity shards means 20% of the data can be rebuilt. It wouldn't be much work.

How do you want to use rs encoding in your program? I wonder how other people use it. I've seen 3 different approaches myself:
1. [data file] -> encode -> [data + parity file]
2. [data file] -> encode -> [data file], [parity file 1], [parity file n]
3. [data file] -> encode -> [data shard 1], [data shard n], [parity shard 1], [parity shard n]

**Comment by prologic** [comment]
I _prefer_ the later myself.

As to how I want to use this in my project? I don't really have a project per se yet, but what I was planning on using it for is in a simple distributed file system with a fuse frontend. I basically want to provide a POSIX file system using FUSE, and for every read/write operation to encode/decode the data as a number of shards with parity across participating nodes.

**Comment by sirMackk** [comment]
@prologic, I think I'll have some time this week to make the changes. It would make another project of mine that uses this code simpler, too.

I was also thinking about the reverse operation, decoding. I was thinking that integrity checking and reconstructing should be done invisibly at the higher-level, which would simplify the decode API to something like

```go
// Decoder checks data & parity integrity and keeps track of that using eg. modified time
func NewDecoder(data io.ReadWriteSeeker, parity []io.ReadWriteSeeker, md Metadata) *Decoder {}

type Decoder interface {
    // check integrity & reconstruct (if needed) on first call, then simply read the data like an ordinary io.Reader
    Read(b []byte) (n int, err error)
}
```
What do you think of that?

> I basically want to provide a POSIX file system using FUSE, and for every read/write operation to encode/decode the data as a number of shards with parity across participating nodes.

This sounds very cool. I'll be watching out for it and see if I have any spare cycles to contribute.

**Comment by prologic** [comment]
I think that looks reasonable.

My main worry is that whole ReadWriteSeeker interface. I'm
 not sure how to deal with this with remote nodes and data streams.

Should I be downloading data and parity streams to local files then performing RS operations on temporary files?

**Comment by sirMackk** [comment]
Yeah, I haven't been able to figure out an efficient way to do RS magic over remote streams. It seems to me that RS operations are pretty IO heavy and could easily multiply traffic 2x-3x compared to just reading a file. Probably not a big issue for smaller files, but a pain with gigabyte-sized files.

I lean toward the solution of downloading data + parity to a local staging area and performing RS operations there because that might be the fastest way to do it from the user's perspective - basically trading more drive space for using less bandwidth).

For clarity, this is from my notes about why the ReadWriteSeeker seems to fit, although I think we could drop the Seeker interface with some extra code:

We need to be able to check integrity, reconstruct, and read data. Split out into go's io interfaces, this maps out to something like this:
1. Check integrity: read (+ seek unless we reopen the file)
2. Reconstruct: read/write.
3. Read: read.

**Comment by prologic** [comment]
Makes sense 👌

**Comment by prologic** [comment]
Any further thoughts/energy into this? I'm _probably_ going to give your library another go and integrate it into something I'm working on.

**Comment by sirMackk** [comment]
Hey @prologic ! Unfortunately I havent had more ideas here and I'm focused on work these days.

**Comment by prologic** [comment]
> Hey @prologic ! Unfortunately I havent had more ideas here and I'm focused on work these days.

Me too! No worries, I'll close this, but I'll let you know via PR(s) if I have any suggestions for improvement.

**Comment by prologic** [comment]
Or rather feel free to close it (_I didn't raise it_)

**Comment by sirMackk** [comment]
> Me too! No worries, I'll close this, but I'll let you know via PR(s) if I have any suggestions for improvement.

@prologic Got it! I'll keep an eye on my github notifications :)
